apiVersion: v1
kind: Secret
metadata:
  name: hw6secret
  labels:
    training: block6
stringData:
  apikey: "c7e9de1e93637eb6157e3ab03698169e0fe392b17204dc42c12c2c55aa607819"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sixth
  labels:
    app: sixth
    training: block6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sixth
      training: block6
  template:
    metadata:
      labels:
        app: sixth
        training: block6
    spec:
      containers:
      - name: app
        image: quay.io/drsylent/cubix/block6/homework:springboot3native
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: hw6secret
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 8081
          name: management
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sixth
  labels:
    app: sixth
    training: block6
spec:
  selector:
    app: sixth
    training: block6
  ports:
    - name: web
      port: 8080
      targetPort: web
